/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum4_2;

/**
 *
 * @author Opal
 */
public class praktikum4_2 extends javax.swing.JFrame {

    /**
     * Creates new form praktikum4_2
     */
    int nilai_a, nilai_b;
    boolean hasil;
    
    public praktikum4_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpertama = new javax.swing.JTextField();
        txtkedua = new javax.swing.JTextField();
        btnsama = new javax.swing.JButton();
        btntidaksama = new javax.swing.JButton();
        btnlebih = new javax.swing.JButton();
        btnkurang = new javax.swing.JButton();
        btnlebihsama = new javax.swing.JButton();
        btnkurangsama = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txthasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NILAI A");

        jLabel2.setText("NILAI B");

        txtpertama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpertamaActionPerformed(evt);
            }
        });

        btnsama.setText("==");
        btnsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsamaActionPerformed(evt);
            }
        });

        btntidaksama.setText("!=");
        btntidaksama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntidaksamaActionPerformed(evt);
            }
        });

        btnlebih.setText(">");
        btnlebih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlebihActionPerformed(evt);
            }
        });

        btnkurang.setText("<");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btnlebihsama.setText(">=");
        btnlebihsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlebihsamaActionPerformed(evt);
            }
        });

        btnkurangsama.setText("<=");
        btnkurangsama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangsamaActionPerformed(evt);
            }
        });

        jLabel3.setText("HASIL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(btnsama))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpertama)
                                    .addComponent(txtkedua, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txthasil)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btntidaksama)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnlebih)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnkurang)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnlebihsama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnkurangsama)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtpertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtkedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsama)
                    .addComponent(btntidaksama)
                    .addComponent(btnlebih)
                    .addComponent(btnkurang)
                    .addComponent(btnlebihsama)
                    .addComponent(btnkurangsama))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a == nilai_b);
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnsamaActionPerformed

    private void btnkurangsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a <= nilai_b);
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnkurangsamaActionPerformed

    private void txtpertamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpertamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpertamaActionPerformed

    private void btntidaksamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntidaksamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a != nilai_b);
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btntidaksamaActionPerformed

    private void btnlebihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlebihActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a > nilai_b);
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnlebihActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());
        
        hasil = (nilai_a < nilai_b);
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnlebihsamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlebihsamaActionPerformed
        // TODO add your handling code here:
        nilai_a = Integer.valueOf(txtpertama.getText());
        nilai_b = Integer.valueOf(txtkedua.getText());

        hasil = (nilai_a >= nilai_b);
        txthasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_btnlebihsamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(praktikum4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(praktikum4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(praktikum4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(praktikum4_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new praktikum4_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnkurangsama;
    private javax.swing.JButton btnlebih;
    private javax.swing.JButton btnlebihsama;
    private javax.swing.JButton btnsama;
    private javax.swing.JButton btntidaksama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtkedua;
    private javax.swing.JTextField txtpertama;
    // End of variables declaration//GEN-END:variables
}
